name: Deploy

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - shell: bash
        run: |
          ls -l
          mkdir -p deploy/woocommerce-oblio
          ls | grep -v deploy | xargs mv -t deploy/woocommerce-oblio
          ls -l

      - name: Zip contents
        uses: vimtor/action-zip@v1
        with:
          files: deploy
          dest: ./packaging/oblio-woocommerce.zip

      - name: create-json
        shell: bash
        run: |
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          JSON_TEMPLATE='${{ secrets.INFO_JSON_TEMPLATE }}'
          echo $JSON_TEMPLATE | sed "s/\[PLUGIN\_VERSION\]/1\.0\.31/g;s/\[PLUGIN\_LAST\_UPDATE\]/$NOW/g" >> ./packaging/info.json

      - name: Pushes to builds repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './packaging'
          target-directory: './woocommerce'
          destination-github-username: 'OblioSoftware'
          destination-repository-name: 'builds'
          target-branch: main